# Generated by Django 5.0.2 on 2026-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'ChatGPT'), (2, 'Gemini')])),
                ('token', models.TextField()),
                ('is_active', models.BooleanField(default=True, unique=True)),
            ],
        ),
    ]
